description: "Relatórios e atividades da disciplina"
title: "Meu Portfólio Acadêmico"
theme: "jekyll-theme-hacker"

# Configuração da navegação
collections:
  pages:
    output: true

# Configuração de navegação
navigation:
  - name: "Página Principal"
    link: "/"
  - name: "Processamento Digital de Imagens"
    link: "/processamento_digital_de_imagens/"
  - name: "Cálculo numérico"
    link: "/calculo_numerico/"
